CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);


-- 수정 = 삭제 + 생성
-- 테이블 삭제
DROP TABLE STUDENT_TBL;


-- TABLE에 데이터를 넣는 방법 → 회원가입(INSERT INTO ~ VALUES)
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('일용자', 11, 1, '서울시 중구');

-- 컬럼명 생략 가능
INSERT INTO STUDENT_TBL VALUES('이용자', 22, 2, '서울시 종로구');
INSERT INTO STUDENT_TBL VALUES('삼용자', 33, 3, '서울시 동대문구');
INSERT INTO STUDENT_TBL VALUES('사용자', 44, 4, '서울시 서대문구');


-- 데이터 내용 수정(UPDATE ~ SET ~ WHERE) GRADE 2번행의 AGE를 99로 바꾼다
UPDATE STUDENT_TBL
SET STUDENT_AGE = 99
WHERE STUDENT_GRADE = 2;


-- 데이터를 삭제해보자 → 회원탈퇴(DELETE FROM ~ WHERE)
DELETE FROM STUDENT_TBL
WHERE STUDENT_AGE = 99;


CREATE TABLE DATATYPE_TBL (
    MOONJJA CHAR(10),
    -- 알파벳 10자, 한글 3글자
    MOONJJAYUL VARCHAR2(100),
    -- 알파벳 100글자, 한글 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALZZA2 TIMESTAMP
);

DESC DATATYPE_TBL;
INSERT INTO DATATYPE_TBL
VALUES('문자', '문자열', 22, SYSDATE, SYSTIMESTAMP);
SELECT MOONJJA, MOONJJAYUL, SOOJJA, NALJJA, NALZZA2
FROM DATATYPE_TBL;

INSERT INTO DATATYPE_TBL
VALUES('문자2', '문자열2', 33, SYSDATE, SYSTIMESTAMP);

UPDATE DATATYPE_TBL
SET MOONJJA = '오라클'
WHERE SOOJJA = 33;

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;


--데이터 조회
SELECT STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS
FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;
