-- UNIQUE 제약조건
INSERT INTO JOB
VALUES('J7', '신입사원');

DROP TABLE JOB;

CREATE TABLE JOB(
    JOB_CODE CHAR(2) UNIQUE,
    JOB_NAME VARCHAR2(35)
);

INSERT INTO JOB VALUES('J1', '대표');
INSERT INTO JOB VALUES('J2', '부사장');
INSERT INTO JOB VALUES('J3', '부장');
INSERT INTO JOB VALUES('J4', '차장');
INSERT INTO JOB VALUES('J5', '과장');
INSERT INTO JOB VALUES('J6', '대리');
INSERT INTO JOB VALUES('J7', '사원');
INSERT INTO JOB VALUES('J7', '신입사원');
-- ORA-00001: unique constraint (KH.SYS_C006999) violated
INSERT INTO JOB VALUES(NULL, '주임');
-- ORA-01400: cannot insert NULL into ("KH"."JOB"."JOB_CODE")


-- PRIMARY KEY 제약조건
-- NULL이 들어가지 않고 중복도 불가하게 해서, 고유식별자로써의 역할을 하도록 함.
CREATE TABLE JOB(
    JOB_CODE CHAR(2) CONSTRAINT JOB_PK PRIMARY KEY,
    -- 제약조건명 지정 ex.JOB_PK
    JOB_NAME VARCHAR2(35)
);


-- NOT NULL 제약조건
INSERT INTO DEPARTMENT
VALUES(NULL, NULL, 'L1');
-- ORA-01400: cannot insert NULL into ("KH"."DEPARTMENT"."DEPT_CODE")
CREATE TABLE DEPARTMENT(
    DEPT_CODE CHAR(2) NOT NULL,
    DEPT_TITLE VARCHAR2(40),
    LOCATION_ID CHAR(2) NOT NULL
);
-- 제약조건 확인
SELECT CONSTRAINT_NAME, CONSTRAINT_YYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'JOB';
-- CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE

-- 제약조건 삭제
ALTER TABLE DEPARTMENT
DROP CONSTRAINT SYS_C006997;

-- 제약조건 추가
ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPT_CODE);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMP_ID);
ALTER TABLE EMPLOYEE
MODIFY EMP_NAME NOT NULL
MODIFY EMP_NO NOT NULL
MODIFY JOB_CODE NOT NULL
MODIFY SAL_LEVEL NOT NULL;

-- 제약조건명 수정
ALTER TABLE DEPARTMENT
RENAME CONSTRAINT DEPARTMENT_PK TO DEPT_ID_PK;


DROP TABLE DEPARTMENT;


COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_TITLE IS '부서명';
COMMENT ON COLUMN DEPARTMENT.LOCATION_ID IS '지역코드';

DESC DEPARTMENT;

-- 컬렁명 수정
ALTER TABLE DEPARTMENT
RENAME COLUMN DEPT_ID TO DEPT_CODE;

-- 테이블명 수정(방법 2가지)
ALTER TABLE DEPARTMENT
RENAME TO DEPARTMENT2;

RENAME DEPARTMENT2 TO DEPARTMENT;

-- 컬럼 데이터타입 수정
ALTER TABLE DEPARTMENT
MODIFY DEPT_TITLE VARCHAR2(40);

-- 컬럼 추가
ALTER TABLE DEPARTMENT
ADD(DEPT_NAME VARCHAR2(30));

-- 컬럼 삭제
ALTER TABLE DEPARTMENT
DROP COLUMN DEPT_NAME;

